=== 2lambda123/starlink/buildsupport/starconf/componentinfo.dtd
<!-- A list of components -->
<!ELEMENT componentlist (component+, manifest*)>

<!-- One component.  The ID attribute is a unique identifier for this
     component, used in, for example, <dependencies> elements of other
     components.  The ID should be the same as the package variable
     declared as the first argument of the configure.ac AC_INIT macro. -->
<!ELEMENT component     (description, path, dependencies, developers?, notes?)>
<!ATTLIST component
        id      ID      #REQUIRED
        >

<!-- Brief description of this component -->
<!ELEMENT description   (#PCDATA)>

<!-- Path to this component in CVS tree -->
<!ELEMENT path          (#PCDATA)>

<!-- List components this component depends on, both those
     required in order to build the component, and those required
     after installation in order to use it.  Both are space-separated
     lists of the IDs given in <component> start-tags.  In both cases
     the list should contain only the direct dependencies, and not
     dependencies of those in turn. -->
<!ELEMENT dependencies  (build?, use?)>
<!ELEMENT build         (#PCDATA)>
<!ELEMENT use           (#PCDATA)>

<!-- A list of developers with an interest in this component -->
<!ELEMENT developers    (person+)>
<!ELEMENT person        (name, email, role?)>
<!ELEMENT name          (#PCDATA)>
<!ELEMENT email         (#PCDATA)>
<!ELEMENT role          (#PCDATA)>

<!-- Any other notes -->
<!ELEMENT notes         (p+)>
<!ELEMENT p             (#PCDATA)>

<!-- The installation manifest for one component.  The component ID
     must be the ID attribute of a <component> element.  However it is
     not declared as an IDREF below, as the <manifest> element is
     sometimes used as a top-level document type. -->
<!ELEMENT manifest      (files)>
<!ATTLIST manifest
        component       CDATA   #REQUIRED
        >

<!-- The list of installed files.  A whitespace-separated list; in
     fact, the files should be separated by newlines, for easy
     subsequent processing, though this is unenforceable here. -->
<!ELEMENT files         (#PCDATA)>

=== 2lambda123/starlink/applications/convert/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="convert">
  <version>1.5-5</version>
  <path>applications/convert</path>
  <description>CONVERT -- format-conversion package</description>
  <abstract><p>
The CONVERT package contains utilities for converting data files between
Starlink's Extensible n-dimensional Data Format (NDF), which is used by most
Starlink applications, and a number of other common data formats.
  </p></abstract>
  <dependencies >
    <build>parsecon</build><build>dtask</build><build>ast</build><build>sae</build><build>chr</build><build>hds</build><build>fio</build><build>cnf</build><build>grp</build><build>mers</build><build>prm</build><build>ndf</build><build>ndg</build><build>par</build><build>psx</build><build>subpar</build><sourceset>star2html</sourceset>
  </dependencies>
  <developers>
    <person>
      <name>Malcolm J. Currie</name>
      <uname>mjc</uname>
    </person>
    <person>
      <name>G.J.Privett</name>
    </person>
    <person>
      <name>A.J.Chipperfield</name>
    </person>
    <person>
      <name>D.S.Berry</name>
      <uname>dsb</uname>
    </person>
    <person>
      <name>A.C.Davenhall</name>
      <uname>acd</uname>
    </person>
  </developers>
  <documentation> sun55</documentation>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <!-- <notes><p></p></notes> -->
</component>
