=== 2lambda123/starlink/buildsupport/starconf/componentinfo.dtd
<!-- A list of components -->
<!ELEMENT componentlist (component+, manifest*)>

<!-- One component.  The ID attribute is a unique identifier for this
     component, used in, for example, <dependencies> elements of other
     components.  The ID should be the same as the package variable
     declared as the first argument of the configure.ac AC_INIT macro. -->
<!ELEMENT component     (description, path, dependencies, developers?, notes?)>
<!ATTLIST component
        id      ID      #REQUIRED
        >

<!-- Brief description of this component -->
<!ELEMENT description   (#PCDATA)>

<!-- Path to this component in CVS tree -->
<!ELEMENT path          (#PCDATA)>

<!-- List components this component depends on, both those
     required in order to build the component, and those required
     after installation in order to use it.  Both are space-separated
     lists of the IDs given in <component> start-tags.  In both cases
     the list should contain only the direct dependencies, and not
     dependencies of those in turn. -->
<!ELEMENT dependencies  (build?, use?)>
<!ELEMENT build         (#PCDATA)>
<!ELEMENT use           (#PCDATA)>

<!-- A list of developers with an interest in this component -->
<!ELEMENT developers    (person+)>
<!ELEMENT person        (name, email, role?)>
<!ELEMENT name          (#PCDATA)>
<!ELEMENT email         (#PCDATA)>
<!ELEMENT role          (#PCDATA)>

<!-- Any other notes -->
<!ELEMENT notes         (p+)>
<!ELEMENT p             (#PCDATA)>

<!-- The installation manifest for one component.  The component ID
     must be the ID attribute of a <component> element.  However it is
     not declared as an IDREF below, as the <manifest> element is
     sometimes used as a top-level document type. -->
<!ELEMENT manifest      (files)>
<!ATTLIST manifest
        component       CDATA   #REQUIRED
        >

<!-- The list of installed files.  A whitespace-separated list; in
     fact, the files should be separated by newlines, for easy
     subsequent processing, though this is unenforceable here. -->
<!ELEMENT files         (#PCDATA)>

=== 2lambda123/starlink/buildsupport/starconf/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">

<component id="starconf" buildsupport="yes">
  <description>Starlink autoconf support</description>
  <path>buildsupport/starconf</path>
  <dependencies>
    <build>automake</build>
  </dependencies>
  <developers>
    <person>
      <name>Norman Gray</name>
      <uname>nxg</uname>
      <email>norman@astro.gla.ac.uk</email>
    </person>
  </developers>
</component>

=== 2lambda123/starlink/applications/figaro/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="figaro" support="S">
  <version>5.6-6</version>
  <path>applications/figaro</path>
  <description>FIGARO general data-reduction system</description>
  <abstract><p>
    Figaro is a general-purpose data reduction package. The programs
    it contains can be used to process a wide range of images and
    spectra.  It is amalgam of traditional Figaro and previously
    separate packages TWODSPEC and SPECDRE.  It does not use Starlink's
    AST infrastructure for world co-ordinate systems.
  </p></abstract>
  <dependencies >
    <build>pcs</build><build option='link'>pda</build><build option='link'>agi</build><build option='link'>grp</build><build option='link'>ndf</build><build option='link'>fio</build><build option='link'>idi</build><build option='link'>shl</build><build option='link'>sla</build><build option='link'>psx</build><sourceset>star2html</sourceset>
  </dependencies>
  <developers>
    <person>
      <name>Keith Shortridge</name>
    </person>
    <person>
      <name>Horst Meyerdierks</name>
    </person>
    <person>
      <name>Martin Clayton</name>
    </person>
    <person>
      <name>Jon Lockley</name>
    </person>
    <person>
      <name>Anne Charles</name>
    </person>
    <person>
      <name>Clive Davenhall</name>
    </person>
    <person>
      <name>Malcolm J Currie</name>
      <uname>mjc</uname>
      <email>mjc@star.rl.ac.uk</email>
      <role>owner</role>
    </person>
    <person>
      <name>Mark Taylor</name>
    </person>
    <person>
      <name>Tim Ash</name>
    </person>
    <person>
      <name>Tim Wilkins</name>
    </person>
    <person>
      <name>Dave Axon</name>
    </person>
    <person>
      <name>John Palmer</name>
    </person>
    <person>
      <name>Anthony Holloway</name>
    </person>
    <person>
      <name>Vito Graffagnino</name>
    </person>
  </developers>
  <documentation> sun86</documentation>
  <bugreports>starlink@jiscmail.ac.uk</bugreports>
  <!-- <notes><p></p></notes> -->
</component>

=== 2lambda123/starlink/libraries/pcs/messys/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="messys">
  <version>3.0</version>
  <path>libraries/pcs/messys</path>
  <description>Message system</description>
  <!-- <abstract><p></p></abstract> -->
  <dependencies>
    <build> sae messgen</build>
    <use> mers ams</use>
  </dependencies>
  <developers>
    <person>
      <name>B D Kelly (REVAD::BDK)</name>
    </person>
    <person>
      <name>Alan J Chipperfield (RLVAD::AJC)</name>
    </person>
  </developers>
  <!-- <documentation>@STAR_DOCUMENTATION@</documentation> -->
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <notes><p>Part of the PCS system</p></notes>
</component>

=== 2lambda123/starlink/libraries/pcs/hdspar/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="hdspar">
  <version>1.0-1</version>
  <path>libraries/pcs/hdspar</path>
  <description>Part of the HDS system.  HDSPAR declares bulk data
    parameters.</description>
  <dependencies>
    <build> sae</build>
    <use> subpar</use>
  </dependencies>
  <developers>
    <person>
      <name>B D Kelly, ROE</name>
    </person>
    <person>
      <name>Alan J Chipperfield</name>
      <uname>ajc</uname>
      <email>a.j.chipperfield@ral.ac.uk</email>
    </person>
  </developers>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <notes><p>Documented in SUN/224, handled in pcs directory</p></notes>
</component>

=== 2lambda123/starlink/applications/obsolete/chart/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="chart" status="obsolete">
  <version>4.0-1</version>
  <path>applications/obsolete/chart</path>
  <description>CHART - Finding chart and stellar data system</description>
  <abstract><p>
The CHART package extracts positions, magnitudes and other data from
certain stellar and non-stellar astronomical catalogues.  The results
may be listed on a terminal or printer, or used to plot finding charts
or perform astrometric reductions.
  </p></abstract>
  <dependencies >
    <build>pcs</build><build option='link'>chr</build><build option='link'>mers</build><build option='link'>sgs</build><build option='link'>gks</build><build option='link'>ifd</build><build option='link'>graphpar</build><build option='link'>pda</build><sourceset>star2html</sourceset>
  </dependencies>
  <developers>
    <person>
      <name>P M Allan</name>
      <uname>pma</uname>
    </person>
    <person>
      <name>Ken Hartley</name>
    </person>
    <person>
      <name>Joe Vickerstaff</name>
    </person>
    <person>
      <name>Tim Wilkins</name>
    </person>
    <person>
      <name>J V Carey</name>
    </person>
    <person>
      <name>Malcolm Currie</name>
    </person>
  </developers>
  <documentation> sun32</documentation>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <!-- <notes><p></p></notes> -->
</component>

=== 2lambda123/starlink/libraries/pcs/sock/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="sock">
  <version>1.0</version>
  <path>libraries/pcs/sock</path>
  <description>Provides a Unix-socket-based message transport system
    for the MSP system</description>
  <dependencies>
    <build> sae messgen</build>
    <use></use>
  </dependencies>
  <developers>
    <person>
      <name>B D Kelly</name>
    </person>
  </developers>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <notes><p>Described in SSN/29</p></notes>
</component>

=== 2lambda123/starlink/libraries/pcs/adamnet/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="adamnet" status="obsolete">
  <version>1.0</version>
  <path>libraries/pcs/adamnet</path>
  <description>Implements the ADAM networking process. It interfaces
  the ADAM intertask communication software on unix to TCP/IP, thereby
  allowing ADAM tasks on different machines to communicate with one
  another. </description>
  <dependencies >
    <build>sae</build><build>messys</build><build>adam</build><build>ams</build><build>msp</build><build>sock</build><sourceset>messgen</sourceset>
  </dependencies>
  <developers>
    <person>
      <name>B.D.Kelly (REVAD::BDK)</name>
    </person>
    <person>
      <name>Brian K McIlwrath</name>
      <uname>bkm</uname>
      <email>b.k.mcilwrath@rl.ac.uk</email>
    </person>
  </developers>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
</component>

=== 2lambda123/starlink/libraries/pcs/misc/component.xml
<?xml version="1.0"?>
<!DOCTYPE component SYSTEM "componentinfo.dtd">
<!-- component.xml.  Generated from component.xml.in by configure. -->

<component id="misc">
  <version>1.4</version>
  <path>libraries/pcs/misc</path>
  <description>Miscellaneous routines required for the Unix build of
    ADAM/HDS</description>
  <dependencies>
    <build> cnf</build>
    <use></use>
  </dependencies>
  <developers>
    <person>
      <name>Alan J Chipperfield</name>
      <uname>ajc</uname>
      <email>a.j.chipperfield@rl.ac.uk</email>
    </person>
  </developers>
  <bugreports>ussc@star.rl.ac.uk</bugreports>
  <notes><p>Documented in SUN/144 in PCS</p></notes>
</component>
